# 第一阶段：编译
FROM golang:1.22 as builder
WORKDIR /app
COPY . .
RUN go mod init docker-demo && CGO_ENABLED=0 GOOS=linux go build -o app main.go

# 第二阶段：runtime
FROM debian:bullseye-slim
WORKDIR /app
COPY --from=builder /app/app .

EXPOSE 8080
CMD ["./app"]

